name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    
    - name: Install PureScript
      run: |
        TAG=$(basename $(curl --location --silent --output /dev/null -w %{url_effective} https://github.com/purescript/purescript/releases/latest))
        curl --location --output $HOME/purescript.tar.gz https://github.com/purescript/purescript/releases/download/$TAG/linux64.tar.gz
        tar -xvf $HOME/purescript.tar.gz -C $HOME/
        chmod a+x $HOME/purescript
    
    - name: Install Spago
      run: npm install -g spago
      
    - name: Build source
      run: npm run build
    
    - name: Build examples
      run: npm run build:examples
    
    - name: Run tests
      run: npm run test
